### ISSUE TITLE
Document magic numbers

### ISSUE THREAD

**Issue by samreid** [phetsims/under-pressure#111]
I've seen several magic numbers in this sim.  What do they mean?  How were they obtained?  Can they be simplified?

For example:
SquarePoolModel.js
```js
    this.inputFaucet = new FaucetModel( new Vector2( 2.7, underPressureModel.skyGroundBoundY - 0.44 ), 1, 0.42 );
    this.outputFaucet = new FaucetModel( new Vector2( 6.6, underPressureModel.skyGroundBoundY + 3.45 ), 1, 0.3 );
...
    this.poolDimensions = {
      x1: 2.3,
      y1: underPressureModel.skyGroundBoundY,
      x2: 6,
      y2: underPressureModel.skyGroundBoundY + 3
    };
```

UnderPressureModel.js (in this case explain in a code comment where this is on the screen relative to other objects)
```js
       rulerPosition: new Vector2( 195, 245 ), // px
```

UnderPressureView.js (what does this do, and why is the value 51 and not something else?)
```js
          pressureReadOffset: 51,
```

Please skim for other cases that need attention as well.  Discovered during #88.

**Comment by samreid** [comment]
We should review this as part of summer 2015 redeploys.  Unassigning until then.

**Comment by jbphet** [comment]
Assigning to @aadish to take a pass through what @notsiddhartha did and to document any remaining occurrences of "magic numbers".  The bulk of the code was moved to the fluid-pressure-and-flow repository, so any changes will take place there.  Note that **only** the under-pressure code will be updated, not the rest of the fluid-pressure-and-flow code.

**Comment by aadish** [comment]
moving over this issue to fluid pressure and flow, most of the magic numbers have been documented for under pressure but would be good to look at again when fluid pressure and flow as a whole moves forward
