### ISSUE TITLE
move this sim's 1 screen to FPAF repo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/under-pressure#118]
Related to: https://github.com/phetsims/fluid-pressure-and-flow/issues/266
Prerequisite: https://github.com/phetsims/under-pressure/issues/117.

The single screen in this sim is part of FPAF. It would be preferable to have it live there, as is done is all other similar situations (Concentration & Beer's Law Lab, pH Scale: Basics & pH Scale, Molecule Shapes: Basics & Molecule Shape,...)

**Comment by pixelzoom** [comment]
This needs to be done before the sim is republished, so that translated strings live in FPAF.

**Comment by aadish** [comment]
the code has been moved to the fpaf's repo

**Comment by aadish** [comment]
fixed closing
