### ISSUE TITLE
Properties should have `Property` suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/under-pressure#119]
Examples of anti pattern:

MysteryPoolModel: this.fluidDensityCustom = new Property( 0 );
MysteryPoolModel: this.gravityCustom = new Property( 0 );

**Comment by pixelzoom** [comment]
Assigning to @jbphet since he's the liaison.

**Comment by jbphet** [comment]
I've changed the two properties called out above to be ```customFluidDensityProperty``` and ```customGravityProperty```.  I don't see any other individually declared properties in the sim code, so I think this issue is now addressed.  Assigning back to @pixelzoom for final verification.

**Comment by pixelzoom** [comment]
:+1: Closing.
