### ISSUE TITLE
icon files are excessively large

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/under-pressure#122]
The icons for scene selection appear in SceneChoiceNode: 

```js
  // images
  var squarePoolImage = require( 'image!UNDER_PRESSURE/square-pool-icon.png' );
  var trapezoidPoolImage = require( 'image!UNDER_PRESSURE/trapezoid-pool-icon.png' );
  var chamberPoolImage = require( 'image!UNDER_PRESSURE/chamber-pool-icon.png' );
  var mysteryPoolImage = require( 'image!UNDER_PRESSURE/mystery-pool-icon.png' );
```

To be the appropriate size for the radio buttons, these icons are being scaled by 0.12, see:

```js
var ICON_SCALE = 0.12; //TODO this is an excessive scale, image files should be scaled down
```

This extreme scaling is likely to result in lousy-looking images on some platforms (e.g. Firefox), and it's bloating the HTML file.  Consider scaling the image files so that less extreme scaling is required in the code.

**Comment by ariel-phet** [comment]
These could be mipmapped is my guess, might be good to take care of

**Comment by aadish** [comment]
the images have been scaled down and now we are using a scale factor of 0.5

**Comment by ariel-phet** [comment]
Scaling working well and image quality appears fine on FF. Closing
