### ISSUE TITLE
Issue "?stringTest=double" overlapping objects

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/under-pressure#123]
Testing for task https://github.com/phetsims/tasks/issues/245

Mystery fluid box 
![screen shot 2015-05-27 at 9 53 37 am](https://cloud.githubusercontent.com/assets/5631059/7840874/772bd42e-0456-11e5-9373-0458bb6dd51c.png)

Water tub covers fluid settings
![screen shot 2015-05-27 at 9 53 48 am](https://cloud.githubusercontent.com/assets/5631059/7840881/85aa2fbe-0456-11e5-9ee6-c611e260d01b.png)

**Comment by phet-steele** [comment]
Applies to phetsims/tasks/issues/479

**Comment by aadish** [comment]
fixed, will be tested during next release

**Comment by ariel-phet** [comment]
All appears fixed, except for mystery fluid combobox, documented in separate issue.
