### ISSUE TITLE
Pressure Gauges are un-returnable

### ISSUE THREAD

**Issue by phet-steele** [phetsims/under-pressure#127]
As of 1/21/2016, the pressure gauges no longer correctly return to their home. This is NOT live, but seen on phettest. Something broke somewhere, and this was discovered while testing for S2015R. Instead of returning to their box, they jump to the top left dev bounds:

![undpre](https://cloud.githubusercontent.com/assets/5863899/12490033/bae0de3a-c030-11e5-91ed-61998406da70.gif)

Tested on Win 8.1 FF

Troubleshooting information:
Name: ‪Under Pressure‬
URL: http://phettest.colorado.edu/under-pressure/under-pressure_en.html?ea&brand=phet&dev
Version: 1.1.0-dev.3 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by aadish** [comment]
fixed, closing
