### ISSUE TITLE
[branch] 1.0-old

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/under-pressure#128]
I changed the 1.0 branch to point to the deployed version (since there were extra commits). This branch stores the old information from 1.0.

Assigning to @jbphet to decide whether it can be removed safely.

See https://github.com/phetsims/yotta/issues/17

**Comment by jbphet** [comment]
@jonathanolson and I discussed this over Skype, and I'm fine with getting rid of this one in order to reduce clutter.

**Comment by jbphet** [comment]
The 1.0-old branch has been deleted, closing.
