### ISSUE TITLE
weights fall too slowly

### ISSUE THREAD

**Issue by jbphet** [phetsims/under-pressure#130]
On the currently published version of this simulation (v1.1.0) as well as on the current master version, the weights that are available for the "chamber pool" fall very slowly when dropped to the ground outside of the fluid in the pool.  In fact, they seem to fall at a rate that is pretty close to how they behave in the pool, which is very un-physical and potentially confusing to users, since these supposedly very heavy weights aren't behaving as real weights would when outside the pool.

**Comment by aadish** [comment]
Link to the commit for the fix
https://github.com/phetsims/fluid-pressure-and-flow/commit/258911288bb2a4d144ffd9bf56fc0e8c4db5f156

Unassigning this for now and will be tested during the testing prcoess

**Comment by phet-steele** [comment]
Performance on Win 10 Chrome looks great, assigning to @ariel-phet for the final say.

**Comment by ariel-phet** [comment]
Looks good to me, especially since this is the speed outside the pool, it just needs to be reasonably physical.
