### ISSUE TITLE
initial dev testing on 1.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/under-pressure#131]
@ariel-phet requested that a dev version of this simulation be published for him to take a look at before starting to move through the release candidate (RC) process.  The dev version can be found here: http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-dev.4/under-pressure_en.html.

@ariel-phet - please take a look and log any issues.  Please also log your opinion about whether we should do a round of dev testing with the QA team after this or go ahead and start putting out RC versions.

**Comment by ariel-phet** [comment]
I am going to meet with @jbphet today and discuss some pixel polishing. I would like to do a dev test on the sim after pixel polishes and before RC.

**Comment by ariel-phet** [comment]
Pixel polishes being implemented, closing
