### ISSUE TITLE
Credits should be updated to include Aadish and QA 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/under-pressure#132]
Please update credits to include @aadish and current QA 

related to https://github.com/phetsims/tasks/issues/585

**Comment by phet-steele** [comment]
@aadish @ariel-phet also lets add "Amanda Davis"?

**Comment by ariel-phet** [comment]
Yes please add "Amanda Davis" to the QA team before publishing

**Comment by phet-steele** [comment]
:+1:
