### ISSUE TITLE
For stringTest=double mystery fluid drop down overlaps pool slighlty

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/under-pressure#133]
The drop down for the mystery fluids overlaps the pool slightly on the "mystery fluid" screen using stringTest=double (seen on Win 7 Chrome)

related to phetsims/tasks#585

![fluid](https://cloud.githubusercontent.com/assets/4051174/14930745/90fcae3c-0e23-11e6-90b7-c3496f798ccd.PNG)

**Comment by alynne-phet** [comment]
@aadish @ariel-phet Fixed in 1.1.0-rc.1
