### ISSUE TITLE
Font size differences for slider labels on Fluid Density and Gravity

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/under-pressure#134]
The font sizes for labels are not consistent on the Fluid Density and Gravity sliders

In particular "gasoline and "Mars" look smaller than corresponding labels

It looks like the published version uses the "gasoline" font size, that wold be acceptable for all

![fonts](https://cloud.githubusercontent.com/assets/4051174/14930821/12f605a0-0e24-11e6-9b8e-d375a964b069.PNG)

Related to https://github.com/phetsims/tasks/issues/585

**Comment by alynne-phet** [comment]
@aadish @ariel-phet Fixed on 1.1.0-rc.1
