### ISSUE TITLE
Slider value labels show mouse hand but are not clickable

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/under-pressure#135]
When hovering over the slider labels "gasoline" "water" honey" "Mars" "Earth" "Jupiter" the pointer turns to a hand as if these are clickable. This behavior should be removed

Related to https://github.com/phetsims/tasks/issues/585

**Comment by alynne-phet** [comment]
@aadish @ariel-phet Fixed on 1.1.0-rc.1.
