### ISSUE TITLE
Touch areas for close buttons on control panels should be enlarged

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/under-pressure#136]
It looks like the touch areas on the close buttons for both the Fluid Density and Gravity control panels could be enlarged slightly (expanded but not overlapping the tweaker touch areas)

![pointerareas](https://cloud.githubusercontent.com/assets/4051174/14931056/c83a0f5a-0e25-11e6-822c-538591ae84ae.PNG)

https://github.com/phetsims/tasks/issues/585

**Comment by aadish** [comment]
me and @jbphet had a discussion about and we can expand the area in the y direction as it will intersect with arrow buttons touch area and for the x direction the whole banner itself is clickable but touch area does not show that so there is no need to expand in that direction

**Comment by ariel-phet** [comment]
It looks to me like there can be a small expansion in the y direction...maybe just 10 percent or so, so it is expanded, but does not overlap the arrow buttons?

**Comment by alynne-phet** [comment]
@ariel-phet Does this look good?

**Comment by ariel-phet** [comment]
Yes, looking good @alynne-phet. Thanks @aadish closing
