### ISSUE TITLE
Edge renders no grass

### ISSUE THREAD

**Issue by phet-steele** [phetsims/under-pressure#137]
Reproduced with `?rootRenderer=canvas`. This makes the weights appear to float:
![nograss](https://cloud.githubusercontent.com/assets/5863899/14962752/a483e29a-105d-11e6-9a3f-0cd9cc385f32.PNG)

@aadish @jonathanolson, ideas? For phetsims/tasks/issues/585.

Troubleshooting information:
Name: ‪Under Pressure‬
URL: http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-dev.5/under-pressure_en.html
Version: 1.1.0-dev.5 2016-04-29 20:29:02 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1600x746
Pixel Ratio: 1/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"5e33541f","branch":"master"},"babel":{"sha":"14af4cf0","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"64ea5afc","branch":"master"},"dot":{"sha":"bf6f038b","branch":"master"},"fluid-pressure-and-flow":{"sha":"2f627795","branch":"master"},"joist":{"sha":"4e95673d","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"c2e3040d","branch":"master"},"scenery-phet":{"sha":"436bf61d","branch":"master"},"sherpa":{"sha":"ab4d5c14","branch":"master"},"sun":{"sha":"a69443fc","branch":"master"},"tandem":{"sha":"0ad35fb7","branch":"master"},"under-pressure":{"sha":"d623ba2c","branch":"master"}}

**Comment by phet-steele** [comment]
Handled in phetsims/scenery/issues/543. Unassigning.

**Comment by jonathanolson** [comment]
Should be fixed, @phet-steele can you confirm?

**Comment by phet-steele** [comment]
@jonathanolson fixed in current master.
