### ISSUE TITLE
Edge - pressure probes can duplicate

### ISSUE THREAD

**Issue by phet-steele** [phetsims/under-pressure#138]
@aadish @jonathanolson I don't really know what's going on here other than I'm pretty confident it's an Edge problem (only repro on chrome with `?rootRenderer=canvas`).

To reproduce, drag out some pressure probes and enable the ruler. Move the ruler around to your heart's content then let go of it, I barely needed to move it in the below video. Trying to move one of the pressure probes around should leave a duplicate behind. This new probe is a complete dud though and can't be moved and will eventually disappear with further interaction with the sim.
![up01](https://cloud.githubusercontent.com/assets/5863899/14968169/bc1b5210-1078-11e6-86ae-96ab18db6fb4.gif)

![manyprobe](https://cloud.githubusercontent.com/assets/5863899/14968164/b638e1c8-1078-11e6-85d6-e30c74672f9a.PNG)

Seen on Win 10 Edge. For phetsims/tasks/issues/585.

Troubleshooting information:
Name: ‪Under Pressure‬
URL: http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-dev.5/under-pressure_en.html?ea
Version: 1.1.0-dev.5 2016-04-29 20:29:02 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 2560x1286
Pixel Ratio: 1/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"5e33541f","branch":"master"},"babel":{"sha":"14af4cf0","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"64ea5afc","branch":"master"},"dot":{"sha":"bf6f038b","branch":"master"},"fluid-pressure-and-flow":{"sha":"2f627795","branch":"master"},"joist":{"sha":"4e95673d","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"c2e3040d","branch":"master"},"scenery-phet":{"sha":"436bf61d","branch":"master"},"sherpa":{"sha":"ab4d5c14","branch":"master"},"sun":{"sha":"a69443fc","branch":"master"},"tandem":{"sha":"0ad35fb7","branch":"master"},"under-pressure":{"sha":"d623ba2c","branch":"master"}}

**Comment by aadish** [comment]
ruler was using css transform which was causing blurr and duplication, fixed that
https://github.com/phetsims/fluid-pressure-and-flow/commit/7dd903fdf72fe229b41ba4e697ce9259d21854d0

**Comment by alynne-phet** [comment]
@aadish @phet-steele Fixed in current master with the above commit.
