### ISSUE TITLE
stringTest=double text overlap

### ISSUE THREAD

**Issue by phet-steele** [phetsims/under-pressure#140]
@aadish `?stringTest=double` reveals some text overlap:

![textoverlap](https://cloud.githubusercontent.com/assets/5863899/14969948/80a8e04e-1082-11e6-9da8-6fbe90a5c07c.PNG)

 Seen on all Win 10 browsers. For phetsims/tasks/issues/585.

Troubleshooting information:
Name: ‪Under Pressure‬
URL: http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-dev.5/under-pressure_en.html
Version: 1.1.0-dev.5 2016-04-29 20:29:02 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
Language: en-US
Window: 1600x767
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"5e33541f","branch":"master"},"babel":{"sha":"14af4cf0","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"64ea5afc","branch":"master"},"dot":{"sha":"bf6f038b","branch":"master"},"fluid-pressure-and-flow":{"sha":"2f627795","branch":"master"},"joist":{"sha":"4e95673d","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"c2e3040d","branch":"master"},"scenery-phet":{"sha":"436bf61d","branch":"master"},"sherpa":{"sha":"ab4d5c14","branch":"master"},"sun":{"sha":"a69443fc","branch":"master"},"tandem":{"sha":"0ad35fb7","branch":"master"},"under-pressure":{"sha":"d623ba2c","branch":"master"}}

**Comment by alynne-phet** [comment]
@aadish @phet-steele Fixed in 1.1.0-rc.1.
