### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/under-pressure#147]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Radio buttons can be hard to press
* Masses don't have pointer areas

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/55913428-e0269d00-5ba1-11e9-85e0-9e304d6bc003.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/55913429-e0269d00-5ba1-11e9-97c1-7ab5156d717f.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/55913430-e0269d00-5ba1-11e9-9aa9-d874665aad20.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/55913431-e0269d00-5ba1-11e9-880f-bd401d75b8f5.png)

**Comment by arouinfar** [comment]
> Radio buttons can be hard to press

The touch areas already include the text. The next step would be vertical dilation, but there's not really room for that. I was able to select radio buttons on the first or second try, so I think that will have to be good enough.

> Masses don't have pointer areas

@KatieWoe I think that just means the touch areas are the physical bounds of the masses. Did you have trouble moving any of these masses?  They seem easy to move on my phone.

**Comment by KatieWoe** [comment]
>  think that just means the touch areas are the physical bounds of the masses.

I figured as much.  I just know that @kathy-phet mentioned the lack of pointer areas in some sims, so I've been pointing them out just in case.

**Comment by arouinfar** [comment]
https://github.com/phetsims/joist/issues/556 will discuss the possibility of automatically showing `pointerAreas` for all UI components, but according to @kathy-phet:
> I don't think its worth  spending time republishing just to make these visible though.
