### ISSUE TITLE
sw build error

### ISSUE THREAD

**Issue by samreid** [phetsims/under-pressure#150]
I got this build error today:

> Build failure: Error: Build aborted, Error: net::ERR_INSUFFICIENT_RESOURCES at https://phet.colorado.edu/sims/html/under-pressure/latest/under-pressure_all.html?locale=en. Sim = under-pressure Version = 1.1.20 Brands = phet Locales = sw Shas = {"comment":"# under-pressure 1.1.20 Mon Aug 08 2022 16:03:50 GMT-0600 (Mountain Daylight Time)","assert":{"sha":"7d27130a4d27da15aa7f8a21bbfb9245288c1b44","branch":"HEAD"},"axon":{"sha":"5e33541f53066f495d1b42efe7344a3c4cb3e3d2","branch":"HEAD"},"brand":{"sha":"24e83e7098317da2bc7be586fd66083ed7d3f2b5","branch":"HEAD"},"chipper":{"sha":"26e0019563429e47ecad8c841393fad136a74ec4","branch":"HEAD"},"dot":{"sha":"bf6f038bca1ea87f23a51c670474438ae282ac2c","branch":"HEAD"},"fluid-pressure-and-flow":{"sha":"46c9948a5445d2374198db6fb726accc474a385c","branch":"HEAD"},"joist":{"sha":"3cfd72e8f9e900a821a2be1463fb4d299f8737c7","branch":"HEAD"},"kite":{"sha":"dce9765e6fcb535970ef17c1a1bcb8db95599b08","branch":"HEAD"},"phet-core":{"sha":"a1f83e9d31975f491f36c7c82de25b821415335b","branch":"HEAD"},"phetcommon":{"sha":"415a4d84e29aa2cc05cb5d278716f07606a98967","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0fe0262594bb06856833b8b16be25deb8","branch":"HEAD"},"scenery":{"sha":"e69ddb7cbbfb132c45ad7da188dc763b878b7c14","branch":"HEAD"},"scenery-phet":{"sha":"a58a48928f1ef6972e32ba0e1eefe1b504dc9e5a","branch":"HEAD"},"sherpa":{"sha":"ab4d5c141bec124c13aeb3d5e0631257da1785bf","branch":"HEAD"},"sun":{"sha":"9f2d40d5ba8cc0f11c9852300e0d7ba59eb06495","branch":"HEAD"},"tandem":{"sha":"0ad35fb75928d18ecc1a429587bed4c605878e89","branch":"HEAD"},"under-pressure":{"sha":"9e1b1ee8f9fcfb94a84db9b9539d79c274f46165","branch":"HEAD"}}
```

**Comment by samreid** [comment]
@mattpen what do you make of the `ERR_INSUFFICIENT_RESOURCES` error?  Is our build server running out of disk space?  Do you think this was a spurious problem?

**Comment by mattpen** [comment]
> @mattpen what do you make of the ERR_INSUFFICIENT_RESOURCES error? Is our build server running out of disk space? Do you think this was a spurious problem?

We are not running out of disk space, this was probably a CPU (thread count?) or memory issue. I'll issue a rebuild of this translation today and see what happens.

**Comment by mattpen** [comment]
I built it today and it finished successfully. I'm going to close this for now, if the problem starts recurring we can reopen the issue and I'll do a deeper investigation.
