### ISSUE TITLE
Text moves when you use faucets. Windows 7, Firefox 27

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/under-pressure#41]
When you use the faucets the text within the tool box in the upper right hand side with (ruler, grid, atmosphere, units, metric, atmospheres, english) translates left and right very slightly. Particularly the spacing of letters increases and decreases as you add or remove fluid.

Tested on a Windows 7 Enterprise 32-bit, on Firefox 27.0

**Comment by jonathanolson** [comment]
Does not happen in Firefox 46.
