### ISSUE TITLE
Weights fall and fluid level rises at a very slow pace. Win 7 IE 10 (Old computer)

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/under-pressure#60]
The weights fall and fluid level rises at a very slow pace on Win 7 with IE 10. Even though the test was done on a old computer, it is strange due to the fact there is no other performance issue. Objects can be moved smoothly , can change screens with out delay, and density/gravity sliders change values continuously. Only the weights fall very slowly, and also the fluid level rises very slowly too.

**Comment by samreid** [comment]
This should be re-evaluated as part of summer 2015 redeploys, unassigning until then.

**Comment by jbphet** [comment]
This sim is nearing redeployment, the performance problem described in this issue should be tested on our usual set of supported platforms at that time and we will make a determination about whether the performance is acceptable or warrants some optimization work.

**Comment by jbphet** [comment]
The slow falling of the weights may actually be a flaw in the model code, see #130.  This issue (#60) shouldn't be retested until after #130 is addressed.

**Comment by ariel-phet** [comment]
IE 10 no longer a supported platform

Tested on IE 11 with http://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.0-dev.5/under-pressure_en.html

Looks acceptable. Closing
