### ISSUE TITLE
Ruler in English Units is broken on iPad

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/under-pressure#65]
This issue is observed on iPad 2, iPad 3, and iPad mini wit ios6 and ios7 .
![image](https://cloud.githubusercontent.com/assets/5631059/3345583/a0b43e2e-f8ba-11e3-9191-17ebe90bf6f3.jpg)

**Comment by pixelzoom** [comment]
I'll assign this to myself, to check whether phetsims/scenery-phet#152 fixed this issue.

**Comment by pixelzoom** [comment]
Verified that ruler with English units is fixed on iPad. Closing.
