### ISSUE TITLE
Pressure Gauge is not an obvious tool

### ISSUE THREAD

**Issue by patricialoeblein** [phetsims/under-pressure#72]
On 8/6/2014 2:04 PM, Patricia J Loeblein wrote:
In our 3 hour workshop at BCCE, we had the chem teachers “play 5 minutes with the sim and share out your discoveries”. Julia chose a physics sim on purpose hoping that the participants would have an experience like students in their classes. The idea turned out very well, however we did discover an issue with the Under Pressure sim. Many teachers did not discover that the pressure gauge was a draggable tool.  It sits by itself in a box that is the same color as the readout tools. A participant spoke to me about the problem during break with the hope that we would consider making the tool more attractive to students. Also, when I showed him that  you can pull out multiple gauges - that was a surprise to him as well. He does already use phet sims in his class, so he remarked that it is unusual for grabbable tools not to be obvious. 
 
I notice that on the full featured sim, on the more complex tab, there are 2 tools (speedometer and pressure gauge), so perhaps we had not noticed the issue during interviews? I think we need to consider changing the tool box color so that the box more clearly denotes something different than the readouts.

**Comment by aadish** [comment]
https://github.com/phetsims/fluid-pressure-and-flow/commit/536f5e3576218e6084722a7c795be68702dc9c56

**Comment by aadish** [comment]
@ariel-phet can you check the master to see if the behavior looks good or some changes are required

**Comment by ariel-phet** [comment]
@aadish I think it would be good for you and I to sit down and do a little pixel polishing here, perhaps on Thursday?

**Comment by aadish** [comment]
@ariel-phet can you pull the latest and see if the changes look fine,

you would need to pull fluid-pressure-and-flow to view the changes

**Comment by ariel-phet** [comment]
@aadish looking good, one minor change. The readout on the pressure gauge should be a bit smaller in the horizontal direction, as shown below (and it should probably have the readout set to this max width):

<img width="199" alt="capture" src="https://cloud.githubusercontent.com/assets/4051174/14434417/e7c13218-ffcf-11e5-919c-56a1fb2434e6.PNG">

**Comment by aadish** [comment]
@ariel-phet please take a look at the master the changes were made

**Comment by ariel-phet** [comment]
@aadish changes on master look good, closing!
