### ISSUE TITLE
Consider changing scene buttons to style used in ESPB

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/under-pressure#74]
Hey @jbphet and @samreid it seems we may want to make the scene buttons in under pressure look more like the scene buttons in ESPB (instead of having the drop shadow). I did not include this look in the mockup given to actualconcepts, since we have not yet made this type of radio button a common code component. 

So we should likely decide on a consistent look for such buttons and the options for having opacity and a dashed stroke, make such buttons a common code component, and then start using this component in sims. I know Aaron did some work on buttons like this for color vision....could he leverage that work into a common code component (might be a good experience for him). And if so, should we create an issue in Sun and assign it to him?

**Comment by samreid** [comment]
It looks like @pixelzoom did this in 437f882dbe455c790e103d26d23bfaea1873426f, closing.
