### ISSUE TITLE
Performance is sluggish when weights are placed in fluid

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/under-pressure#86]
When weights are placed in the fluid, the settling time is long and the performance is choppy (the weights appear on scene 3). Performance issues seen on Win 7 Chrome.

**Comment by alynne-phet** [comment]
@ariel-phet @aadish This is back on all of the iPads. Performance drops when dragging out pressure gauges and makes the settling time so long that the weight appears to never settle. @phet-steele had the weights bouncing for 30 minutes before getting impatient and reloading the tab. 
Steps for reliable reproduction:
1. Go to third scene
2. Slide gravity to max (Jupiter)
3. Slide fluid density to max (honey)
4. Add 250 kg weight to liquid
5. Quickly drag out pressure gauges and place in liquid

**Comment by aadish** [comment]
reference the commit https://github.com/phetsims/fluid-pressure-and-flow/commit/747e1b70e8b754a502b2556ec79d2ff4f26a5eac

**Comment by phet-steele** [comment]
@aadish sliders and settling time performing well!
