### ISSUE TITLE
English ruler and grid don't match up

### ISSUE THREAD

**Issue by arnabp** [phetsims/under-pressure#87]
![under pressure feet](https://cloud.githubusercontent.com/assets/8583364/4512155/0a0cd9ec-4b3d-11e4-8929-551cb6febe93.PNG)

This problem doesn't appear to show up for the metric system.

**Comment by samreid** [comment]
This should be re-evaluated as part of summer 2015 redeploys, unassigning until then.

**Comment by aadish** [comment]
fixed, will be tested in the next round

**Comment by ariel-phet** [comment]
verified fixed. Closing
