### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by samreid** [phetsims/under-pressure#88]
@ariel-phet said dev testing is complete, and Under Pressure is ready for code review.

**Comment by jbphet** [comment]
@samreid - Under Pressure is being prepped for Summer 2015 Redeploy, and is quite close.  @aadish and I are not sure what to do with this issue.  Any recommendations?

**Comment by samreid** [comment]
Most of my commits above were straightforward, the outstanding work was tracked in related issues, many of which are closed and all of which are tracked elsewhere.  Hence this issue can be closed.  I suspect that this sim will need a fresh code review at some point, since our review process has changed.  But it should be up for discussion when that review happens (doesn't need to block publication of i18n version).

**Comment by jbphet** [comment]
Agreed that this should undergo a full re-review at some point. @ariel-phet has said that he plans to assign someone to the whole Fluid Pressure and Flow suite relatively soon, but well after the republication of a translatable version of Under Pressure. Closing.
